---
spring:
  application:
    environment: systest

bevisgenerator:
  byob-service:
    base-url: https://byob-service.eidas2sandkasse.dev
  issuer-server:
    base-url: https://issuer-server.eidas2sandkasse.dev

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
