---
spring:
  application:
    environment: systest

bevisgenerator:
  issuer-server:
    base-url: https://byob-service.eidas2sandkasse.dev

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
