---
spring:
  application:
    environment: test

bevisgenerator:
  features:
    allow-create-bevistyper: false
  byob-service:
    base-url: https://byob-service.test.eidas2sandkasse.net
  issuer-server:
    base-url: https://utsteder.test.eidas2sandkasse.net

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
