---
spring:
  application:
    environment: systest

bevisgenerator:
  issuer-server:
    base-url: https://utsteder.eidas2sandkasse.dev

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
